# COMBAT

# This node will calculate the players' Clicks Per Second in real time
[highcps]
enabled = true
historic = 10 # amount of clicks used to calculate the CPS

[[highcps.punishers]]
punisher = "combat"
concurrent = true # will be activated even if a higher check is
min_cps = 14.0
add = 1.0

# RENDER

# This node will make ineffective healthbar mods
[healthbar]
enabled = true