# COMBAT

# This node will calculate the players' Clicks Per Second in real time
[highcps]
enabled = true
historic = 10 # amount of clicks used to calculate the CPS

[[highcps.punishers]]
punisher = "combat"
concurrent = true # will be activated even if a higher check is
min_cps = 14.0
add = 1.0

[speed]
enabled = true
rollback = true # cancels suspicious movements
tolerance = 1.08 # accepts up to 8% more than the vanilla limit

[speed.punisher]
punisher = "movement"
concurrent = true # will be activated even if a higher check is
add = 1.0

# This node will analyse the distance between the players and the entities they are attacking
[reach]
enabled = true

# RENDER

# This node will make ineffective healthbar mods
[healthbar]
enabled = true