[combat]

decrease = 1 # decrease every 5 minutes

[[combat.action]]
threshold = 10
alert = "{user} is suspicious"

[[combat.action]]
threshold = 50
alert = "{player} has an extremely suspicious behavior"

[[combat.action]]
threshold = 100
commands = [
    "ban {player} 'You have been automatically banned for cheating'"
]