[plugin]
prefix = "<gradient:#F5867B:#FAC987>Guardian</gradient> <#282B3F>| "

[commands]
not_a_player = "you must be a player to use this command"
not_enough_players = "there are not enough players connected to the server"
target_frozen = "the target player has been successfully frozen"
target_unfrozen = "the target player has been successfully unfrozen"
player_frozen = "you have been successfully frozen"
player_unfrozen = "you have been successfully unfrozen"
target_killed = "the target player has been successfully killed"
target_banned = "the target player has been successfully banned"

[items]
teleport_item_name = "<#47b594>Random teleportation to a player"
freeze_item_name = "<#4fcdf0>Freeze the targeted player"
kill_item_name = "<#e36659>Kill the targeted player"
ban_item_name = "<#805753>Ban the targeted player"
info_item_name = "<#c2c9ab>Show targeted player stats"

[infoview]
title = "<player> informations"
author = "<gradient:#F5867B:#FAC987>Guardian</gradient>"
punisher_line = "<punisher> : <score>"