[plugin]
prefix = "<gradient:#F5867B:#FAC987>Guardian</gradient> <#282B3F>| "
journal_prefix = "<gradient:#F5867B:#FAC987>Journal</gradient> <#282B3F>| "
node_log = """<hover:show_text:\"<#f39c12>click to inspect\"><click:run_command:/guardian inspect \
            <player>><color:#b5e3eb><b><player></b></color></click></hover> fired <node>: <data>"""

[commands]
help = """Available commands
\"<gray>fill journal command\"><click:SUGGEST_COMMAND:/guardian journal ><#6f737d>/g \
<#b8bbc2>journal <#fa8943>type <#43fa8c>enable</click></hover>  <#6f737d>»<#b8bbc2> subscribe to journal logs
<hover:show_text:\"<gray>fill info command\"><click:SUGGEST_COMMAND:/guardian info ><#6f737d>/g \
<#b8bbc2>info <#43c9fa>player</click></hover>  <#6f737d>»<#b8bbc2> show player informations
<hover:show_text:\"<gray>fill freeze command\"><click:SUGGEST_COMMAND:/guardian freeze ><#6f737d>/g \
<#b8bbc2>freeze <#43c9fa>player</click></hover>  <#6f737d>»<#b8bbc2> toggle player freeze
<hover:show_text:\"<gray>fill inspect command\"><click:SUGGEST_COMMAND:/guardian inspect><#6f737d>/g \
<#b8bbc2>inspect</click></hover>   <#6f737d>»<#b8bbc2> toggle inspect mode"""
not_a_player = "you must be a player to use this command"
not_enough_players = "there are not enough players connected to the server"
target_frozen = "the target player has been successfully frozen"
target_unfrozen = "the target player has been successfully unfrozen"
player_frozen = "you have been successfully frozen"
player_unfrozen = "you have been successfully unfrozen"
target_killed = "the target player has been successfully killed"
target_banned = "the target player has been successfully banned"
journal_subscribed = "you registered to the <name> journal"
journal_already_subscribed = "you were already registered to the <name> journal"
journal_unsubscribed = "you unregistered from the <name> journal"
journal_not_subscribed = "you were not registered to the <name> journal"

[items]
teleport_item_name = "<#47b594>Random teleportation to a player"
freeze_item_name = "<#4fcdf0>Freeze the targeted player"
kill_item_name = "<#e36659>Kill the targeted player"
ban_item_name = "<#805753>Ban the targeted player"
info_item_name = "<#c2c9ab>Show targeted player stats"
exit_item_name = "<#8a76db>Exit inspect mode"

[infoview]
title = "<gradient:#F5867B:#FAC987><bold><player> info</gradient><reset>"
punisher_line = "<#6B6B6B><underlined><punisher></underlined>: <#5C5C5C><score>"